# Generated by Django 3.2.13 on 2025-09-09 06:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='reserved_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='reservation',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reservation',
            name='num_people',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_type',
            field=models.CharField(choices=[('テーブル席', 'テーブル席'), ('カウンター席', 'カウンター席')], default='テーブル席', max_length=20),
        ),
    ]
